### ISSUE TITLE
Error: Internal Exception

### ISSUE THREAD

**Issue by AntharesGG** [ebshimizu/stats-of-the-storm#303] opened 2020-10-05 03:29 UTC
Hello there.

I've uploaded multiple replays, however two of them got the "Error: Internal Exception" on the status sorting tab when I clicked "Parser".

The replayes are attached bellow. Is there something that can be done?

[HotS Replays - Error Internal Exception.zip](https://github.com/ebshimizu/stats-of-the-storm/files/5325053/HotS.Replays.-.Error.Internal.Exception.zip)

Thanks in advance. :)

**Comment by ebshimizu** [comment] 2020-10-05 18:11
I can take a look. Most of the internal exception errors are caused by incomplete replays (not finding a winner/loser for the match).

**Comment by AntharesGG** [comment] 2020-10-06 18:24
Thank you ebshimizu :)

**Comment by ebshimizu** [comment] 2020-10-07 15:26
Ok so at least for one replay the draft data seems invalid. The replay contains 9 pick events and one of those pick events seems to indicate that someone with a user ID that isn't actually playing in the game (is an observer) picked a hero so not sure what's happening there. I added a fallback to the parser to just ignore draft data if this happens, so the game should still parse but the draft order will be lost. Should be fixed in the next update for sots.

**Comment by ebshimizu** [comment] 2020-10-08 18:36
marking this one as closed with release of new version

**Closed by ebshimizu** 2020-10-08 18:36 UTC

**Comment by AntharesGG** [comment] 2020-10-09 19:41
Thank you ebshimizu, sorry for my delay on answering, but thank you a lot for your effort :)
