### ISSUE TITLE
Player Detail Filter results in blank screen

### ISSUE THREAD

**Issue by darinshepit** [ebshimizu/stats-of-the-storm#237] opened 2018-09-08 03:35 UTC
I just found out about the app and I'm super excited to dig into it.

After parsing my recent replays (1197) I loaded up the Player Detail screen and searched for my ID. It took a while, but showed up. However, after turning on a filter -- for example, just wanting to see Hero Type: Assassin -- it starts the Loading cycle then goes to a blank screen. Even the window UI disappears, so I need to force close it and restart the app.

I've reproduced this a few times, though it has worked for me at least once.

_I'm running 2.3.9 on Windows 7, 64 bit_

**Comment by ebshimizu** [comment] 2018-09-09 01:30
Ok ran a few tests and I'm unable to reproduce the issue with my local database. This error is likely happening due to a missing piece of info in the parsed replay files, but since I can't reproduce it, i dunno what it missed.
Please zip up your database folder and send me a link so I can take a look. If you need help locating that folder, let me know and I'll help you out with that.

**Comment by ebshimizu** [comment] 2018-09-10 04:45
Looked at this again with a larger database, and there's definitely some unusually large memory use going in to some of these queries. My 2800 replay DB allocated a peak of 8GB while attempting to filter out matches from a single hero. Obviously that's a bit concerning, however I'm not quite sure what the cause is yet.

**Comment by darinshepit** [comment] 2018-09-10 05:26
You beat me by less than an hour...

Here's my DB zip: https://www.dropbox.com/s/k3br90j0ecltvxi/stats-of-the-storm.zip?dl=0

Often, I'll set my filters up, run the search, then alt-tab to something else while it loads. There may be no correlation, but I noticed that this bug happens more often when the window is in the background.

**Comment by ebshimizu** [comment] 2018-09-10 06:10
Bit of a note to myself so i don't forget in the morning:

Some of the offending functions causing excessive memory use appear to be related to clearing the "friends" and "rivals" tables containing a list of players that the specified player has played with frequently. In a personal database, this is often a list of every single user in the entire db. The problem only comes up when attempting to clear these tables (???).

**Comment by ebshimizu** [comment] 2018-09-11 00:54
Update: I believe I can do a pretty easy drop-in replacement for some of the heavier tables. Will swap those in and see if performance improves for large databases.

**Comment by ebshimizu** [comment] 2018-09-12 00:18
Final update: This will be resolved in the next version (likely release when the balance patch hits).

The issue was indeed how a few needlessly large tables were being updated in the app. They have been transitioned over to datatables.net versions, and more of the tables with standard formatting will be transferred over in the coming days. This should result in a general performance boost for the app once all possible tables have been transferred. Until then, Player Details will see the most noticeable gain.

You'll be able to track the implementation status of the tables at #151.

**Closed by ebshimizu** 2018-09-12 00:18 UTC
Labels: bug
